### ISSUE TITLE
Link to USB-C cable used in pictures?

### ISSUE THREAD

**Issue by rriqbal** [macroxue/keyboard-diy#1]
I am concerned I will cut open a usb-c cable and find out it is not color coded.

Also is it important if it gen 2 or not? Or did you just test gen 2? 

Thanks and regards,

**Comment by macroxue** [comment]
I've been using only "USB 3.1 Type-C Gen 2 Cable" made by Cable Matters. I suspect early Gen may miss some wires but I have no proof.
https://www.amazon.com/Cable-Matters-USB-IF-Certified-Delivery/dp/B01L0F6IK4/ref=sr_1_3?dchild=1&keywords=usb-c%2Bgen%2B2%2Bcable%2Bby%2BCable%2BMatters&qid=1601556925&sr=8-3&th=1
